const utils = {
    TradeNumber: "Trade Number",
    BuyerName: "Buyer Name",
    SellerName: "Seller Name",
    BuyerID: "Buyer ID",
    SellerID: "Seller ID",
    TradeStatus: "Trade Status",
    TradeType: "Trade Type",
    MarketType: "Market Type",
    Price: "Price",
    PriceUOM: "Price UOM",
    Quantity: "Quantity",
    QuantityUOM: "Quantity UOM",
    TotalQuantity: "Total Quantity",
    TotalQuantityUOM: "Total Quantity UOM",
    TradeDate: "Trade Date",
    StartDate: "Start Date",
    EndDate: "End Date",
    ProductCode: "Product Code",
    DeliveryLocation: "Delivery Location",
    PaymetDays: "Paymet Days",
    PaymentTerms: "Payment Terms",
    Mot: "Mot",
    Owner: "Owner ID",
    OwnerName: "Owner Name",
    CreatorUser: "Created By",
    CreationTimestamp: "Creation Time",
}
module.exports = utils;